require 'pry'
require 'yaml'

require_relative './lib/modules/validator.rb'
require_relative './lib/modules/statistics.rb'
require_relative './lib/modules/storage.rb'
require_relative './lib/entities/drinks/cappuccino.rb'
require_relative './lib/entities/drinks/espresso.rb'
require_relative './lib/entities/drinks/americano.rb'
require_relative './lib/entities/ingredients/application_ingredient.rb'
require_relative './lib/entities/ingredients/milk.rb'
require_relative './lib/entities/ingredients/water.rb'
require_relative './lib/entities/ingredients/coffee_beans.rb'
require_relative './lib/entities/user.rb'
require_relative './lib/entities/order.rb'

require_relative './lib/errors/class_error.rb'
require_relative './lib/errors/string_error.rb'
require_relative './lib/errors/ingredients_error.rb'

require_relative './lib/entities/coffee_machine.rb'
