require 'yaml'

require_relative './lib/modules/validator'
require_relative './lib/modules/statistics'
require_relative './lib/modules/storage'
require_relative './lib/entities/drinks/cappuccino'
require_relative './lib/entities/drinks/espresso'
require_relative './lib/entities/drinks/americano'
require_relative './lib/entities/ingredients/application_ingredient'
require_relative './lib/entities/ingredients/milk'
require_relative './lib/entities/ingredients/water'
require_relative './lib/entities/ingredients/coffee_beans'
require_relative './lib/entities/user'
require_relative './lib/entities/order'

require_relative './lib/errors/class_error'
require_relative './lib/errors/string_error'
require_relative './lib/errors/ingredients_error'

require_relative './lib/entities/coffee_machine'
